name: pos
description: "Luna POS - Point of Sales Application"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Navigation
  go_router: ^17.3.0

  # HTTP Client
  dio: ^5.9.0
  retrofit: ^4.9.2

  # Functional programming
  equatable: ^2.0.7

  # State Management
  flutter_bloc: ^9.1.1


  # Dependency Injection
  get_it: ^9.1.0
  injectable: ^3.0.0

  # Firebase
  firebase_core: ^4.13.0
  cloud_firestore: ^6.8.0
  firebase_messaging: ^16.5.0

  # Local Storage
  shared_preferences: ^2.5.3

  # Network Image
  cached_network_image: ^3.4.1

  # Loading Overlay
  loader_overlay: ^5.0.0

  # Permission
  permission_handler: ^13.0.0

  # Localization
  intl: ^0.20.2

  # Env
  flutter_dotenv: ^6.0.1

  # Utilities
  dartz: ^0.10.1
  logger: ^2.6.2
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  flutter_svg: ^2.0.17

  # Database (Drift)
  drift: ^2.20.1
  sqlite3_flutter_libs: ^0.6.0+eol
  sqlite3: ^3.5.1
  path_provider: ^2.1.4
  path: ^1.9.0


  # Icons
  cupertino_icons: ^1.0.8
  toastification: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  injectable_generator: ^3.1.1
  retrofit_generator: ^10.2.8
  json_serializable: ^6.9.5
  flutter_gen_runner: ^5.15.0
  drift_dev: ^2.20.1


flutter:
  generate: true
  uses-material-design: true

  assets:
    - envs/dev.env
    - envs/prod.env
    - assets/color/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true

  fonts:
    outputs:
      class_name: AppFonts

  colors:
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: AppColors
